### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by Batarian711** [Kermalis/PokemonBattleEngine#156]
Hi. I am a graphic designer. I volunteer to design a logo for open source projects. I can design it for you to use it in the text file. What dou you say?

**Comment by Kermalis** [comment]
Hello, what are your ideas for the logo? I haven't thought much about a logo, and I don't know what would be original for a Pokémon fan project. Perhaps something unique could be similar to this: https://cdn4.techly.com.au/wp-content/uploads/2016/07/pokein-650x345.jpg

Where we have a Pokéball with a Hydreigon printed on it in a nice style. Hopefully that doesn't sound like too much, but if you are up for that idea, or you have your own ideas, I would be very interested.

**Comment by Batarian711** [comment]
Pokeball can be a nice design. I'il send it to you when I'm finished.

**Comment by Batarian711** [comment]
I designed Pokeball in the simplest and minimalist way. What is your opinion?
![po](https://user-images.githubusercontent.com/41051393/55592885-96255d80-5742-11e9-863b-461f16bb6406.jpg)

**Comment by Kermalis** [comment]
I think it should be a lot more detailed and incorporate Hydreigon in some way...
